//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HGPS.Data.ModelsEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int Id { get; set; }
        public int LocationId { get; set; }
        public int Year { get; set; }
        public System.DateTime Date { get; set; }
        public string AltDate { get; set; }
        public string Hours { get; set; }
        public string Price { get; set; }
        public string GroupPriceDetail { get; set; }
    
        public virtual Location Location { get; set; }
    }
}
